
    version: "2"

    services:
      # Back End Service
      app-server:
        image: "gold-pocket:latest"
        build:
          context: .
        container_name: gold-pocket
        ports:
          - 8888:8888
        depends_on:
          - db
        environment:
          - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
          - SPRING_DATASOURCE_USERNAME=compose-postgres
          - SPRING_DATASOURCE_PASSWORD=compose-postgres
          - SPRING_JPA_HIBERNATE_DDL_AUTO=update
        networks:
          - backend
          - frontend

      # Front End Service
      app-client:
        image: "angular-pocket:latest"
        build: .
        ports:
          - 81:80
        container_name: gold-pocket-fe
        restart: always
        depends_on:
          - app-server
        networks:
          - frontend
        links:
          - app-server

      # Postgre SQL
      db:
        image: "postgres:13.1-alpine"
        container_name: postgre-SQL
        environment:
          - POSTGRES_USER=compose-postgres
          - POSTGRES_PASSWORD=compose-postgres
        networks:
          - backend

    # Network
    networks:
      backend:
      frontend:
